version: '3'

services:
  db:
    image: postgres
    env_file:
      - ./.envs/.postgres
    volumes:
      - ./postgres/postgres-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
  web:
    build: .
    command: 
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8001"
    env_file:
      - ./.envs/.postgres
    volumes:
      - . :/django324

    ports:
      - "8001:8001"
    depends_on:
      - db