# Generated by Django 4.0.3 on 2022-03-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialCampismo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
